# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `audits1984` gem.
# Please instead update this file by running `bin/tapioca gem audits1984`.


# source://audits1984//lib/audits1984/version.rb#1
module Audits1984
  # source://audits1984//lib/audits1984.rb#9
  def auditor_class; end

  # source://audits1984//lib/audits1984.rb#9
  def auditor_class=(val); end

  # source://audits1984//lib/audits1984.rb#10
  def auditor_name_attribute; end

  # source://audits1984//lib/audits1984.rb#10
  def auditor_name_attribute=(val); end

  # source://audits1984//lib/audits1984.rb#11
  def base_controller_class; end

  # source://audits1984//lib/audits1984.rb#11
  def base_controller_class=(val); end

  class << self
    # source://audits1984//lib/audits1984.rb#9
    def auditor_class; end

    # source://audits1984//lib/audits1984.rb#9
    def auditor_class=(val); end

    # source://audits1984//lib/audits1984.rb#10
    def auditor_name_attribute; end

    # source://audits1984//lib/audits1984.rb#10
    def auditor_name_attribute=(val); end

    # source://audits1984//lib/audits1984.rb#11
    def base_controller_class; end

    # source://audits1984//lib/audits1984.rb#11
    def base_controller_class=(val); end

    # source://railties/7.1.3.4/lib/rails/engine.rb#412
    def railtie_helpers_paths; end

    # source://railties/7.1.3.4/lib/rails/engine.rb#395
    def railtie_namespace; end

    # source://railties/7.1.3.4/lib/rails/engine.rb#416
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://railties/7.1.3.4/lib/rails/engine.rb#401
    def table_name_prefix; end

    # source://railties/7.1.3.4/lib/rails/engine.rb#408
    def use_relative_model_naming?; end
  end
end

module Audits1984::ApplicationHelper
  include ::ActionDispatch::Routing::PolymorphicRoutes
  include ::ActionDispatch::Routing::UrlFor

  def auditor_name_for(auditor); end

  # source://actionpack/7.1.3.4/lib/action_dispatch/routing/url_for.rb#99
  def default_url_options=(val); end

  def format_date(date); end
  def format_date_and_time(date); end
  def highlight_code(source); end
  def highlighted_code_from(commands); end
  def sensitive_session_decoration(session); end

  class << self
    # source://actionpack/7.1.3.4/lib/action_dispatch/routing/route_set.rb#584
    def _routes; end

    # source://actionpack/7.1.3.4/lib/action_dispatch/routing/url_for.rb#99
    def default_url_options=(val); end
  end
end

class Audits1984::ApplicationJob < ::ActiveJob::Base; end

class Audits1984::ApplicationMailer < ::ActionMailer::Base
  private

  # source://actionview/7.1.3.4/lib/action_view/layouts.rb#330
  def _layout(lookup_context, formats); end

  class << self
    # source://actionview/7.1.3.4/lib/action_view/layouts.rb#211
    def _layout; end

    # source://actionview/7.1.3.4/lib/action_view/layouts.rb#212
    def _layout_conditions; end

    # source://actionmailer/7.1.3.4/lib/action_mailer/base.rb#502
    def default_params; end
  end
end

class Audits1984::ApplicationRecord < ::ActiveRecord::Base
  include ::Audits1984::ApplicationRecord::GeneratedAttributeMethods
  include ::Audits1984::ApplicationRecord::GeneratedAssociationMethods

  class << self
    # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
    def _validators; end

    # source://activerecord/7.1.3.4/lib/active_record/enum.rb#167
    def defined_enums; end
  end
end

module Audits1984::ApplicationRecord::GeneratedAssociationMethods; end
module Audits1984::ApplicationRecord::GeneratedAttributeMethods; end

class Audits1984::Current < ::ActiveSupport::CurrentAttributes
  class << self
    # source://activesupport/7.1.3.4/lib/active_support/current_attributes.rb#127
    def auditor; end

    # source://activesupport/7.1.3.4/lib/active_support/current_attributes.rb#127
    def auditor=(value); end
  end
end

# source://audits1984//lib/audits1984/engine.rb#5
class Audits1984::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

class Audits1984::FilteredSessions
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::NameOfPerson::HasPersonName
  include ::ActiveModel::Access
  include ::ActiveModel::Model
  include ::ActiveModel::AttributeRegistration
  include ::ActiveModel::AttributeMethods
  include ::ActiveModel::Attributes
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods
  extend ::NameOfPerson::HasPersonName::ClassMethods
  extend ::ActiveModel::AttributeRegistration::ClassMethods
  extend ::ActiveModel::AttributeMethods::ClassMethods
  extend ::ActiveModel::Attributes::ClassMethods

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
  def __callbacks; end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
  def __callbacks?; end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#951
  def _run_validate_callbacks(&block); end

  # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#963
  def _validate_callbacks; end

  # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
  def _validators; end

  # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
  def _validators?; end

  def all; end

  # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#72
  def attribute_aliases; end

  # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#72
  def attribute_aliases?; end

  # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#73
  def attribute_method_patterns; end

  # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#73
  def attribute_method_patterns?; end

  # source://activemodel/7.1.3.4/lib/active_model/naming.rb#255
  def model_name(&block); end

  # source://activemodel/7.1.3.4/lib/active_model/conversion.rb#32
  def param_delimiter=(_arg0); end

  def pending_session_after(session); end
  def to_h; end

  # source://activemodel/7.1.3.4/lib/active_model/validations.rb#67
  def validation_context; end

  private

  # source://activemodel/7.1.3.4/lib/active_model/validations.rb#67
  def validation_context=(_arg0); end

  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks=(value); end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks?; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#955
    def _validate_callbacks; end

    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#959
    def _validate_callbacks=(value); end

    # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
    def _validators; end

    # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
    def _validators=(value); end

    # source://activemodel/7.1.3.4/lib/active_model/validations.rb#71
    def _validators?; end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#72
    def attribute_aliases; end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#72
    def attribute_aliases=(value); end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#72
    def attribute_aliases?; end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#73
    def attribute_method_patterns; end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#73
    def attribute_method_patterns=(value); end

    # source://activemodel/7.1.3.4/lib/active_model/attribute_methods.rb#73
    def attribute_method_patterns?; end

    # source://activemodel/7.1.3.4/lib/active_model/conversion.rb#32
    def param_delimiter; end

    # source://activemodel/7.1.3.4/lib/active_model/conversion.rb#32
    def param_delimiter=(value); end

    # source://activemodel/7.1.3.4/lib/active_model/conversion.rb#32
    def param_delimiter?; end

    def resume(attributes); end
  end
end

module Audits1984::FilteredSessionsScoped
  extend ::ActiveSupport::Concern

  private

  def set_filtered_sessions; end
end

module Audits1984::Session; end

module Audits1984::Session::Auditable
  extend ::ActiveSupport::Concern
end

module Audits1984::Session::Iterable
  extend ::ActiveSupport::Concern

  def each_batch_of_commands_grouped_by_sensitive_access; end
end

# source://audits1984//lib/audits1984/version.rb#2
Audits1984::VERSION = T.let(T.unsafe(nil), String)
