# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `babel-source` gem.
# Please instead update this file by running `bin/tapioca gem babel-source`.


# source://babel-source//lib/babel/source.rb#1
module Babel; end

# source://babel-source//lib/babel/source.rb#2
module Babel::Source; end

# source://babel-source//lib/babel/source.rb#4
Babel::Source::DATE = T.let(T.unsafe(nil), Time)

# source://babel-source//lib/babel/source.rb#5
Babel::Source::PATH = T.let(T.unsafe(nil), String)

# source://babel-source//lib/babel/source.rb#3
Babel::Source::VERSION = T.let(T.unsafe(nil), String)
