# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `babel-transpiler` gem.
# Please instead update this file by running `bin/tapioca gem babel-transpiler`.


# source://babel-transpiler//lib/babel/transpiler/version.rb#1
module Babel; end

# source://babel-transpiler//lib/babel/transpiler/version.rb#2
module Babel::Transpiler
  class << self
    # source://babel-transpiler//lib/babel/transpiler.rb#23
    def context; end

    # source://babel-transpiler//lib/babel/transpiler.rb#19
    def script_path; end

    # source://babel-transpiler//lib/babel/transpiler.rb#15
    def source_path; end

    # source://babel-transpiler//lib/babel/transpiler.rb#11
    def source_version; end

    # source://babel-transpiler//lib/babel/transpiler.rb#27
    def transform(code, options = T.unsafe(nil)); end

    # source://babel-transpiler//lib/babel/transpiler.rb#7
    def version; end
  end
end

# source://babel-transpiler//lib/babel/transpiler/version.rb#3
Babel::Transpiler::VERSION = T.let(T.unsafe(nil), String)
