# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bulma-rails` gem.
# Please instead update this file by running `bin/tapioca gem bulma-rails`.


# source://bulma-rails//lib/bulma-rails.rb#1
module Bulma; end

# source://bulma-rails//lib/bulma-rails.rb#2
class Bulma::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end
