# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `query_count` gem.
# Please instead update this file by running `bin/tapioca gem query_count`.


# https://github.com/rails/rails/blob/master/activerecord/lib/active_record/railties/controller_runtime.rb
#
# source://query_count//lib/query_count/counter.rb#4
module QueryCount; end

# source://query_count//lib/query_count/controller_runtime.rb#3
module QueryCount::ControllerRuntime
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::QueryCount::ControllerRuntime::ClassMethods

  private

  # source://query_count//lib/query_count/controller_runtime.rb#29
  def append_info_to_payload(payload); end

  # source://query_count//lib/query_count/controller_runtime.rb#23
  def process_action(action, *args); end
end

# source://query_count//lib/query_count/controller_runtime.rb#6
module QueryCount::ControllerRuntime::ClassMethods
  # source://query_count//lib/query_count/controller_runtime.rb#7
  def log_process_action(payload); end
end

# source://query_count//lib/query_count/counter.rb#5
class QueryCount::Counter < ::ActiveSupport::LogSubscriber
  # source://query_count//lib/query_count/counter.rb#38
  def sql(event); end

  class << self
    # source://query_count//lib/query_count/counter.rb#12
    def counter; end

    # source://query_count//lib/query_count/counter.rb#8
    def counter=(value); end

    # source://query_count//lib/query_count/counter.rb#20
    def counter_cache; end

    # source://query_count//lib/query_count/counter.rb#16
    def counter_cache=(value); end

    # source://query_count//lib/query_count/counter.rb#24
    def reset_counter; end

    # source://query_count//lib/query_count/counter.rb#31
    def reset_counter_cache; end
  end
end

# source://query_count//lib/query_count/counter.rb#6
QueryCount::Counter::IGNORE_PAYLOAD_NAMES = T.let(T.unsafe(nil), Array)

# source://query_count//lib/query_count/railtie.rb#5
class QueryCount::Railtie < ::Rails::Railtie; end

# source://query_count//lib/query_count/version.rb#2
QueryCount::VERSION = T.let(T.unsafe(nil), String)
