gemfile: Gemfile

PreCommit:
  Fasterer:
    enabled: true
    exclude:
      - "vendor/**/*.rb"
      - "db/schema.rb"

  BundleAudit:
    enabled: true
    flags: ["--update"]

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
    command: ["bundle", "exec", "rubocop"]
