gemfile: Gemfile

PreCommit:
  # TODO: Re-enable RuboCop once we have a chance to fix all the warnings
  # RuboCop:
  #   enabled: true
  #   on_warn: fail

  Standard:
    enabled: true
    all_files: true

  Fasterer:
    enabled: true

  BundleAudit:
    enabled: true
