gemfile: Gemfile

PreCommit:
  # TODO: add standard linter

  Fasterer:
    enabled: true

  BundleAudit:
    enabled: true

  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
    command: ["bundle", "exec", "rubocop"]
