version: "3.1"

services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: greenhouse_internal-site
      POSTGRES_PASSWORD: internalsupersecretsecurepassword
      POSTGRES_DB: greenhouse
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  postgres_data:
