# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: greenhouse_development

test:
  <<: *default
  database: greenhouse_test

production:
  <<: *default
  database: greenhouse_production
