# Name of your application. Used to uniquely configure containers.
service: greenhouse

# Name of the container image.
image: jaspermayone/greenhouse

# Deploy to these servers.
servers:
  web:
    hosts:
      - 10.100.0.19
    labels:
      traefik.http.routers.my_awesome_app.entrypoints: websecure
      traefik.http.routers.my_awesome_app.rule: Host(`greenhouse.directory`)
    options:
      network: "private" # This is important!

  job:
    hosts:
      - 10.100.0.19
    cmd: bundle exec rake solid_queue:start
    options:
      network: "private" # This is important!

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: jaspermayone

  # Always use an access token rather than real password when possible.
  password: KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: "production"
    POSTGRES_USER: "greenhouse"
    POSTGRES_DB: "greenhouse_production"
    POSTGRES_HOST: "greenhouse-db"
    # - REDIS_URL: "redis://greenhouse-redis:6379/0"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - KAMAL_REGISTRY_PASSWORD

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:15
    host: 10.100.0.19
    container_name: greenhouse-db # Ensure this matches the POSTGRES_HOST value
    env:
      clear:
        POSTGRES_USER: "greenhouse"
        POSTGRES_DB: "greenhouse_production"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: "private" # This is important!

  # redis:
  #   image: redis:7.0
  #   host: 10.100.0.19
  #   # port: 6379 # Remove this line!
  #   directories:
  #     - data:/data
  #   options:
  #     network: "private" # This is important!

# Use a different ssh user than root
ssh:
  # user: jasper
# Configure builder setup.
builder:
  args:
    RUBY_VERSION: 3.3.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Configure the role used to determine the primary_host. This host takes
# deploy locks, runs health checks during the deploy, and follow logs, etc.
#
# Caution: there's no support for role renaming yet, so be careful to cleanup
#          the previous role on the deployed hosts.
# primary_role: web

# Controls if we abort when see a role with no hosts. Disabling this may be
# useful for more complex deploy configurations.
#
# allow_empty_roles: false
